image: framgia/laravel-workspace

cache:
  paths:
    - vendor/
    - node_modules/

phpcs:
  script:
    - phpcs --standard=Framgia app/

phpunit:
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - touch storage/testing.sqlite
    - php artisan migrate --env=testing --database=sqlite_testing --force
    - php ./vendor/bin/phpunit --coverage-text --colors=never
  only:
    - master
